spring:
  cloud:
    consul:
      host: 127.0.0.1                  
      port: 8500
      discovery:
        prefer-ip-address: true
        enabled: true
        register: true
        service-name: ${spring.application.name}
        health-check-path: ${management.context-path}/health
        health-check-interval: 10s
        health-check-tomeout: 1s
        
